### ISSUE TITLE
Notion Test Issue

### ISSUE THREAD

**Issue by Silthus** [Silthus/minecraft-server-template#3]
Fancy Test Body
- with formatting

and `inline code`

```yaml
and: formatted
code:
 - foo
 - bar
```

- [ ] Check me!
